"""
Exhaustive word and phrase lists for dash/em-dash context detection in llm_output_scrub.

These lists are imported by dash_nlp.py and can be extended as needed.
"""

# List of interruption phrases for abrupt breaks (should be exhaustive for English)
interruption_phrases = [
    "never mind",
    "forget it",
    "whatever",
    "anyway",
    "actually",
    "well",
    "oh",
    "um",
    "uh",
    "er",
    "hmm",
    "so",
    "but",
    "however",
    "nevertheless",
    "meanwhile",
    "suddenly",
    "unexpectedly",
    "what",
    "wait",
    "hold on",
    "listen",
    "look",
    "stop",
    "pause",
    "hang on",
    "excuse me",
    "by the way",
    "in fact",
    "besides",
    "incidentally",
    "as a matter of fact",
    "on the other hand",
    "on second thought",
    "speaking of which",
    "come to think of it",
    "now that i think about it",
    "oh yeah",
    "oh right",
    "wait a minute",
]

# List of emphasis words/phrases (should be exhaustive for common English adverbs/markers)
emphasis_words = [
    "amazingly",
    "incredibly",
    "unfortunately",
    "fortunately",
    "interestingly",
    "surprisingly",
    "obviously",
    "clearly",
    "apparently",
    "evidently",
    "actually",
    "basically",
    "essentially",
    "fundamentally",
    "ultimately",
    "finally",
    "at last",
    "in fact",
    "indeed",
    "truly",
    "really",
    "however",
    "nevertheless",
    "nonetheless",
    "meanwhile",
    "suddenly",
    "unexpectedly",
    "seriously",
    "frankly",
    "honestly",
    "undoubtedly",
    "certainly",
    "surely",
    "remarkably",
    "notably",
    "importantly",
    "significantly",
    "consequently",
    "therefore",
    "thus",
    "hence",
    "additionally",
    "furthermore",
    "moreover",
    "likewise",
    "similarly",
    "not surprisingly",
    "as expected",
    "as usual",
    "as always",
    "as a result",
    "absolutely",
    "definitely",
    "naturally",
    "of course",
    "predictably",
    "inevitably",
    "eventually",
]

# List of common English compound word prefixes/suffixes (should be exhaustive for standard compounds)
compound_patterns = [
    "self-",
    "pre-",
    "post-",
    "anti-",
    "pro-",
    "co-",
    "non-",
    "re-",
    "un-",
    "over-",
    "under-",
    "multi-",
    "inter-",
    "trans-",
    "sub-",
    "super-",
    "counter-",
    "cross-",
    "mid-",
    "out-",
    "up-",
    "down-",
    "semi-",
    "mini-",
    "maxi-",
    "micro-",
    "macro-",
    "neo-",
    "pseudo-",
    "quasi-",
    "vice-",
    "ex-",
    "-based",
    "-oriented",
    "-friendly",
    "-free",
    "-less",
    "-like",
    "-wise",
    "-proof",
    "-type",
    "-grade",
    "-size",
    "-shaped",
    "-style",
    "-wide",
    "-level",
    "-rate",
    "-class",
    "-driven",
    "-centric",
    "-related",
    "-rich",
    "-heavy",
    "-light",
    "-sized",
    "-powered",
    "-enabled",
    "-focused",
    "-bound",
    "-headed",
    "-looking",
    "-seeking",
    "-serving",
    "-spanning",
    "-tolerant",
    "-resistant",
    "-sensitive",
    "-specific",
    "-dependent",
    "-independent",
    "-inclusive",
    "-exclusive",
    "-intensive",
    "-extensive",
    "-worthy",
    "-able",
    "-ible",
    "-ous",
    "-ful",
    "-ish",
    "-esque",
    "-ian",
    "-ist",
    "-ism",
]
